# NEC(6701)株価情報
NEC(6701)の [**HP**](https://finance.yahoo.co.jp/quote/6701.T/history) から株価情報の最初のページのみ Pandas で取得
![株価情報](./Pandas-Exercises1.png)

In [1]:
# ライブラリのインポート
import pandas as pd
from datetime import datetime as dt

# リクエスト送信とデータ取得
url = 'https://finance.yahoo.co.jp/quote/6701.T/history'
data = pd.read_html(url, header=0)

# 欠損値(NaN)を削除
data[0].dropna(inplace=True)

# 日付型のフィールド「修正日付」を追加
data[0]['修正日付'] = [dt.strptime(val, "%Y年%m月%d日") for val in data[0]['日付']]

# 不要なフィールド「日付」を削除
data[0].drop('日付', axis=1, inplace=True)

# フィールド「修正日付」をインデックス指定
data[0].set_index('修正日付', inplace=True)

# フィールド「修正日付」をキーに昇順にソート
data[0].sort_index(ascending=True, inplace=True)

In [4]:
data[0]

              始値    高値    安値    終値      出来高  調整後終値*
修正日付
2022-08-08  4885  4910  4850  4890  1033300    4890
2022-08-09  4935  5010  4930  5010  1514100    5010
2022-08-10  4970  4975  4900  4945   881600    4945
2022-08-12  4960  5010  4945  5010  1197100    5010
2022-08-15  5040  5040  4990  4995   660100    4995
2022-08-16  4930  4940  4880  4900  1266200    4900
2022-08-17  4935  4985  4910  4985  1231200    4985
2022-08-18  4995  4995  4940  4985   726400    4985
2022-08-19  4965  4985  4950  4965   754100    4965
2022-08-22  4910  4975  4895  4975   852700    4975
2022-08-23  4965  4975  4930  4935   693600    4935
2022-08-24  4900  4915  4860  4885   900900    4885
2022-08-25  4900  4905  4860  4890   697900    4890
2022-08-26  4895  4910  4865  4870   590900    4870
2022-08-29  4800  4805  4765  4775   883900    4775
2022-08-30  5010  5110  5010  5060  3523300    5060
2022-08-31  5060  5140  5010  5100  2281700    5100
2022-09-01  5050  5080  4990  4995  1252000    4995
2022-09-02  4990  5000  4915  4955  1177200    4955
2022-09-05  4945  4960  4905  4940   830500    4940